name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 0 * * *' # Runs daily at 12:30 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "22f3000155@ds.study.iitm.ac.in"

      - name: Make a Dummy Commit
        run: |
          echo "Automated commit on $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Automated commit on $(date)"
          git push
